isaackogan/TikTokLive

- TikTokLive/client/base.py
closes #63 
I tested locally on python 3.7 environment that this code works in both the main thread and a new thread. 
test code for a new thread:
```py
import threading
import time
import asyncio
from TikTokLive import TikTokLiveClient
def start_tiktok():
client = TikTokLiveClient(unique_id='@xxx')
@client.on("comment")
async def on_connect(event):
print(event.comment)
client.run()
thread = threading.Thread(target=start_tiktok)
thread.daemon = True
thread.start()
time.sleep(10)
```
> fix error when running on a new thread

- TikTokLive/client/base.py
Some live streams do not have hls addresses, you can use flv addresses to download live streams
> fix(download): add flv live stream

- TikTokLive/client/base.py
This pull request introduces an update to the signal handling mechanism for the `stop_download` functionality, extending support to Unix, Linux, and macOS operating systems. Previously, application's signal handling was limited to Windows environments, utilizing `signal.CTRL_BREAK_EVENT`. This update brings cross-platform compatibility.
> Enhanced stop_download signal handling for Unix/Linux/MacOS

- TikTokLive/client/client.py
When pass a room_id directly to start, the TikTokWebClient's parmas is not updated. So it needs mannual update for the room_id param.
> Fix room_id params

- TikTokLive/proto/proto_utils.py
This fixes the depreciation of \d in re.
`python3.12/site-packages/TikTokLive/proto/proto_utils.py:84: SyntaxWarning: invalid escape sequence '\d' MEMBER_LEVEL_BADGE_PATTERN: re.Pattern = re.compile("fans_badge_icon_lv(\d+)_v")`
`python3.12/site-packages/TikTokLive/proto/proto_utils.py:85: SyntaxWarning: invalid escape sequence '\d' GIFTER_LEVEL_BADGE_PATTERN: re.Pattern = re.compile("grade_badge_icon_lite_lv(\d+)_v")`
Reference: https://stackoverflow.com/questions/50504500/deprecationwarning-invalid-escape-sequence-what-to-use-instead-of-d
> Library re \d depreciation

- TikTokLive/client/client.py
With this quick fix, the library specified above can finally be properly imported. At least in vs code.
> Proper import of AsyncIOEventEmitter

- TikTokLive/client/client.py
/venv_debug/lib/python3.12/site-packages/TikTokLive/client/client.py:408: RuntimeWarning: coroutine 'TikTokLiveClient.disconnect' was never awaited
self.disconnect()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
> bugfix: await client disconnect

- TikTokLive/client/client.py
- scripts/proto/src/enums.proto
See: https://github.com/zerodytrash/TikTok-Live-Connector
Source: https://github.com/zerodytrash/TikTok-Live-Connector/blob/3277f0707dd4702650e682eed0bcd06b936de7e3/src/index.js#L531
```tiktokLiveConnection.on('streamEnd', (actionId) => {
if (actionId === 3) {
console.log('Stream ended by user');
}
if (actionId === 4) {
console.log('Stream ended by platform moderator (ban)');
}
})```
> feat(client): added suspended protobuf and event handle

- TikTokLive/client/ws/ws_client.py
- setup.py
- Change websockets_proxy to version 0.1.3 to fix this: https://github.com/racinette/websockets_proxy/commit/749581e4dc389cbcf78a8a3841b0060983f712bb
> - Fix ws_proxy authentication

- TikTokLive/client/web/web_settings.py
Fixes
[flv @ 000002498ba1fac0] Video codec (c) is not implemented.
> hotfix(client): flv codec problem

- TikTokLive/client/web/routes/download_video.py
- `VideoFetchFormat` was previously used as a key for `record_url_data`
- fixed a bug that record_format other than flv could not be used
> fixed reference to record_format value

- README.md
This PR expands the basic description of some events.  Information may not be 100% complete, but matches my current observations.
Additionally, while I didn't edit it in this PR - SubscribeEvent does seem to trigger without a sessionId.
> Expand the description of some events

- TikTokLive/client/client.py
awaiting _event_loop_task may raise exception from WebcastIterator and it results in the following processes not to be executed.
just catch and ignore exceptions on disconnecting
> handle error from event loop on disconnecting

- TikTokLive/client/web/routes/fetch_video_data.py
```python
client.web.fetch_video_data.start(
output_fp=f"{event.unique_id}-%03d.mp4",
room_info=client.room_info,
output_format="mp4",
outputs={"segment": "-f", "60": "-segment_time", "1": "-reset_timestamps"},
record_for=360
)
```
> refact(fetch_video_data) outputs construction to improve argument merging order

- TikTokLive/client/web/routes/fetch_video_data.py
```python
client.web.fetch_video_data.start(
output_fp=f"{event.unique_id}-%03d.mp4",
room_info=client.room_info,
output_format="mp4",
outputs={"segment": "-f", "60": "-segment_time", "1": "-reset_timestamps"},
record_for=360
)
```
```python
client.web.fetch_video_data.start(
output_fp=f"{event.unique_id}-%03d.mp4",
room_info=client.room_info,
output_format="mp4",
outputs = {
"-f": "segment",
"-segment_time": "60",
"-reset_timestamps": "1",
"-reconnect": "1"
},
record_for=360
)
```
ffmpy swaps key and value: https://github.com/Ch00k/ffmpy/blob/a55e54988bdcc6638ca1d8c0120389efd36d1cea/ffmpy/ffmpy.py#L194
> bugfix(fetch_video_data) fix order to prevent duplicate keys

- TikTokLive/client/web/routes/fetch_video_data.py
To get the filename of a recording:
```python
client.web.fetch_video_data.output_filename
```
None if no recording
> feat(fetch_video_data) add output_filename property

- TikTokLive/proto/custom_proto.py
- TikTokLive/proto/proto_utils.py
Fix issue where AttributeError: 'BadgeStruct' object has no attribute 'display_type' occurs when retrieving gifter_level, and resolve the root cause.
> Fix: Cannot retrieve gifter_level

- pyproject.toml
`pip uninstall -y tiktoklive; pip install 'git+https://github.com/isaackogan/TikTokLive#egg=TikTokLive'`
```
python tiktoklive_with_ssid.py
Traceback (most recent call last):
File "tiktoklive_with_ssid.py", line 11, in <module>
from TikTokLive import TikTokLiveClient
File "venv/lib/python3.12/site-packages/TikTokLive/__init__.py", line 1, in <module>
from .client.client import TikTokLiveClient
ModuleNotFoundError: No module named 'TikTokLive.client'
```
Working
> fix: update pyproject.toml to include subpackages using find

- TikTokLive/client/ws/ws_client.py
- TikTokLive/events/proto_events.py
- TikTokLive/proto/custom_proto.py
`TypeError: ExtendedGift.__init__() missing 1 required positional argument: 'proto_gift'`
- Remove deprecated `display_id` warnings and legacy shims in `ExtendedUser`
- Refactor `ExtendedGift` constructor to handle optional `proto_gift` gracefully
- Simplify `GiftEvent.gift` to return base `Gift` type instead of `ExtendedGift`
- Replace debug `print` with proper logger call in WebSocket client
> refact: clean up deprecated code and improve initialization logic

- TikTokLive/client/client.py
- TikTokLive/client/web/routes/resolve_user_id.py
- TikTokLive/client/web/web_client.py
`client: TikTokLiveClient = TikTokLiveClient(unique_id="@6701514161706304513", is_userid=True)`
This resolves 6701514161706304513 to tv_asahi_news
What's the point of that? You can change the unique_id, but not the user ID.
> feat(client): add user ID resolution support

- TikTokLive/client/ws/ws_client.py
sending ack WebcastPushFrame(log_id=ID, payload_type='ack', payload=b'{"server_fetch_time":TIME,"push_time":TIME,"msg_type":"r","seq_id":SEQ_ID,"is_from_ws_proxy":false}')
No output as intended
> refactor(logging): replace print with debug logger for ack messages
